
server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native # Use local file system for configurations
  cloud:
    config:
      server:
        native:
          search-locations: file:./config/ # Path to configuration files

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
